package Proxy;

import java.util.List;
import java.util.ArrayList;

public class UtilisateursNFP121 extends Utilisateurs{
    private static final List<String> LISTE_NFP121 =  new ArrayList<String>();
    static{
        LISTE_NFP121.add("Damien");
        LISTE_NFP121.add("Frédéric");
        LISTE_NFP121.add("Thomas");
        LISTE_NFP121.add("Manonmany");
        LISTE_NFP121.add("Lydia");
        LISTE_NFP121.add("Cyril");
        LISTE_NFP121.add("Adrien");
        LISTE_NFP121.add("Thierry");
        LISTE_NFP121.add("William");
        LISTE_NFP121.add("Sébastien");
        LISTE_NFP121.add("Mouna");
        LISTE_NFP121.add("Roland");
        LISTE_NFP121.add("Romain");
        LISTE_NFP121.add("Abdurrahman");
        LISTE_NFP121.add("Silvano");
        LISTE_NFP121.add("Andy");
        LISTE_NFP121.add("Ramzi");
        LISTE_NFP121.add("Abdoulaye");
        LISTE_NFP121.add("Moussa");
        LISTE_NFP121.add("Julien");
        LISTE_NFP121.add("Eldjouher");
        LISTE_NFP121.add("Fatima Zahra");
        LISTE_NFP121.add("Jocelyn");
        LISTE_NFP121.add("Arnaud");
        LISTE_NFP121.add("Stéfan");
        LISTE_NFP121.add("Nicolas");
        LISTE_NFP121.add("Stephane");
        LISTE_NFP121.add("Nivethan");
        LISTE_NFP121.add("Benjamin");
        LISTE_NFP121.add("Philippe");
        LISTE_NFP121.add("Clothilde");
        LISTE_NFP121.add("Adrien");
        LISTE_NFP121.add("Robin");
        LISTE_NFP121.add("Nathanaël");
        LISTE_NFP121.add("Ghislin");
        LISTE_NFP121.add("Chloé");
        LISTE_NFP121.add("Mélanie");
        LISTE_NFP121.add("Mohammed");
        LISTE_NFP121.add("Guillaume");
        LISTE_NFP121.add("Jean-François");
        LISTE_NFP121.add("Alexandre");
        LISTE_NFP121.add("Jacky");
        LISTE_NFP121.add("Fabien");
        LISTE_NFP121.add("Kenzo");
        LISTE_NFP121.add("Pierre-Alexandre");
        LISTE_NFP121.add("Alice");
        LISTE_NFP121.add("Maria");
        LISTE_NFP121.add("Rémy");
        LISTE_NFP121.add("Amine Hakim");
        LISTE_NFP121.add("Gabriel");
        LISTE_NFP121.add("Laura");
        LISTE_NFP121.add("Bertrand");
        LISTE_NFP121.add("Laurence");
        LISTE_NFP121.add("Said");
        LISTE_NFP121.add("Marie");
        LISTE_NFP121.add("Annette");
        LISTE_NFP121.add("Laurent");
        LISTE_NFP121.add("Jean-Luc");
        LISTE_NFP121.add("Bahia");
        LISTE_NFP121.add("Lamine");
        LISTE_NFP121.add("Elsa");
        LISTE_NFP121.add("Darvel");
        LISTE_NFP121.add("Valentin");
        LISTE_NFP121.add("Alain");
        LISTE_NFP121.add("Djanfar");
        LISTE_NFP121.add("Seng-Ly");
        LISTE_NFP121.add("Fabien");
        LISTE_NFP121.add("Alexandre");
        LISTE_NFP121.add("Céline");
        LISTE_NFP121.add("Emmanuel");
        LISTE_NFP121.add("Jean");
        LISTE_NFP121.add("Julien");
        LISTE_NFP121.add("Clea");
        LISTE_NFP121.add("Yannick");
        LISTE_NFP121.add("Korentin");
        LISTE_NFP121.add("Benoit");
        LISTE_NFP121.add("Mathilde");
        LISTE_NFP121.add("Fiezdine");
        LISTE_NFP121.add("Ralph");
        LISTE_NFP121.add("Vincent");
        LISTE_NFP121.add("Nicolas");
        LISTE_NFP121.add("Patrick");
        LISTE_NFP121.add("Hervé");
        LISTE_NFP121.add("Mehdi");
        LISTE_NFP121.add("Witan");
        LISTE_NFP121.add("Maxime");
        LISTE_NFP121.add("Stephane");
        LISTE_NFP121.add("Edwin");
        LISTE_NFP121.add("Sergei");
        LISTE_NFP121.add("Narek");
    }
    public List<String> agrees (){
        return LISTE_NFP121;
    }
}